import os
import json
from openai import OpenAI
from dotenv import load_dotenv
import psycopg2
from manage import DB_PARAMS
# Load environment variables
load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def name_saver():
    """Fetches all phone models from database and saves to CSV file"""
    conn = None
    model_data = set()
    try:
        # Connect to the database
        conn = psycopg2.connect(**DB_PARAMS)
        cur = conn.cursor()
        
        # Get all models from products table
        query = """SELECT model FROM shopify_products"""
        cur.execute(query)
        data = cur.fetchall()
        
        
        # Write to CSV file
        with open("phonemodal.csv", "w", encoding="utf-8") as file:
            file.truncate() # Delete everything in this file
            for row in data:
                if row[0]:  # Check if model is not None/empty
                    model_data.add(row[0])
            
            for i in model_data:
                file.write(i + ",")    
        
        print(f"Saved {len(model_data)} models to phonemodal.csv")
    
    except Exception as e:
        print(f"Error in name_saver: {e}")
    finally:
        if conn:
            cur.close()
            conn.close()
            
def name_extractor(file_path: str,phone_modal: str):
    prompt = """
        You are given two inputs:
        1️⃣ A phone name as text input
        2️⃣ A CSV data

        Your task is to:
        Read the CSV data
        Search for the given phone name in all columns
        If the phone name exists, return the exact matching word/value from the CSV
        If the phone name does not exist, respond with: "Phone name not found"
        
        Return your response in JSON format like: {"phone_model": "matched value or null"}
    """


    with open(file_path, "r", encoding="utf-8") as file:
        file_data = file.read()
    # Call OpenAI API
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # Use gpt-4o or gpt-4o-mini
            messages=[
                {
                    "role": "system",
                    "content": prompt
                },
                {
                    "role": "user",
                    "content": f"Phone name to search: {phone_modal}\n\nCSV Data:\n{file_data}" 
                }
            ],
            response_format={"type": "json_object"}
        )
        
        # Parse the JSON string response into a Python dictionary
        return json.loads(response.choices[0].message.content)

def Get_Product_Name(file_path: str,phone_modal: str):
    try:
        # local db of phone names and their variations
        devices = {
            "SAMSUNG TAB S9ULTRA": [
            "samsung tab s9 ultra",
            "samsung s9 ultra tab",
            "tab s9 ultra",
            "tab s9ultra",
            "s9 ultra tab",
            "s9ultra tab",
            "samsung tab s9ultra",
            "samsung galaxy tab s9 ultra",
            "galaxy tab s9 ultra",
            "galaxy s9 ultra tab",
            "s9 ultra tablet",
            "s9ultra tablet",
            "samsung s9 ultra tablet",
            "tab s9",
            "s9 ultra",
            "samsung tab s9",
            "galaxy tab s9ultra",
            "s9ultra",
            "samsung s9ultra"
        ],

            "SAMSUNG FOLD6": [
            "samsung fold 6",
            "samsung z fold 6",
            "galaxy fold 6",
            "galaxy z fold 6",
            "z fold 6",
            "zfold 6",
            "zfold6",
            "fold 6",
            "fold6",
            "samsung fold6",
            "samsung zfold6",
            "galaxy fold6",
            "galaxy zfold 6",
            "z fold6",
            "samsung galaxy fold 6",
            "samsung galaxy z fold 6",
            "fold samsung 6",
            "samsung fold",
            "fold z 6"
        ],
            "LENOVO TAB 4 X304N (10)": [
            "lenovo tab 4",
            "lenovo tab4",
            "tab 4 lenovo",
            "lenovo tab 4 10",
            "lenovo tab 4 10 inch",
            "lenovo tab 4 x304n",
            "tab 4 x304n",
            "x304n",
            "lenovo x304n",
            "lenovo tab x304n",
            "tab x304n",
            "lenovo tab4 x304n",
            "lenovo tab 4 10.1",
            "tab 4 10",
            "lenovo tablet tab 4",
            "tab4",
            "lenovo tab four",
            "lenovo tab 4 tablet",
            "tab 4 tablet"
        ],
            "ONEPLUS PAD": [
            "oneplus pad",
            "one plus pad",
            "onepluspad",
            "one pluspad",
            "op pad",
            "1+ pad",
            "oneplus tablet",
            "one plus tablet",
            "oneplus tab",
            "one plus tab",
            "pad oneplus",
            "pad one plus",
            "oneplus pad tablet",
            "onepluspad tablet",
            "oneplus",
            "op tablet",
            "oneplus pad device",
            "pad by oneplus"
        ],
        "APPLE IWATCH 44MM": [
            "apple watch 44mm",
            "apple watch 44 mm",
            "iwatch 44mm",
            "i watch 44mm",
            "i watch 44 mm",
            "watch 44mm",
            "watch 44 mm",
            "apple iwatch 44mm",
            "apple i watch 44mm",
            "apple watch 44",
            "iwatch 44",
            "watch 44",
            "apple smartwatch 44mm",
            "apple watch 44mm size",
            "44mm apple watch",
            "44 mm apple watch",
            "iwatch44mm",
            "applewatch 44mm",
            "apple watch44mm",
            "apple watch size 44mm"
        ],
        "IPHONE 15": [
            "ip15",
            "iphone15",
            "15",
            "iphone 15",
            "i phone 15",
            "iphone15",
            "i phone15",
            "apple iphone 15",
            "apple iphone15",
            "apple i phone 15",
            "iphone fifteen",
            "iphone 15 phone",
            "iphone 15 mobile",
            "iphone 15 model",
            "iphone15 phone",
            "15 iphone",
            "iphone latest 15",
            "new iphone 15",
            "iphone15 apple",
            "iphone 15 device",
            "iphone fifteen apple"
        ],
        "IPHONE 14PLUS": [
            "ip14plus",
            "iphone14 plus",
            "14 plus",
            "14+",
            "14plus",
            "iphone 14plus",
            "iphone14plus",
            "i phone 14 plus",
            "apple iphone 14 plus",
            "apple iphone14plus",
            "14 plus iphone",
            "14plus iphone",
            "iphone 14 +",
            "iphone14 +",
            "iphone plus 14",
            "iphone 14 plus phone",
            "iphone 14 plus mobile",
            "iphone fourteen plus",
            "iphone14plus apple",
            "iphone 14plus model",
            "iphone 14 big",
            "14 iphone plus"
        ],
        "SAMSUNG S24+": [
            "samsung s24+",
            "samsung s24 plus",
            "galaxy s24 plus",
            "galaxy s24+",
            "s24 plus",
            "s24+",
            "s24plus",
            "samsung s24plus",
            "galaxy s24plus",
            "samsung galaxy s24 plus",
            "samsung galaxy s24+",
            "s24 plus samsung",
            "s24 samsung plus",
            "samsung s24 +",
            "samsung s24 + plus",
            "samsung s24 phone",
            "s24 plus phone",
            "s24 plus mobile",
            "s24+ samsung"
        ],
        "SAMSUNG TAB S9FE+": [
            "tab s9 fe plus",
            "tab s9 fe+",
            "samsung tab s9 fe",
            "samsung tab s9 fe+",
            "samsung s9 fe+",
            "samsung s9 fe plus",
            "galaxy tab s9 fe plus",
            "galaxy tab s9 fe+",
            "tab s9fe plus",
            "tab s9fe+",
            "s9 fe plus tab",
            "s9fe plus tab",
            "s9 fe tab",
            "s9fe tab",
            "s9fe+ tab",
            "tab s9fe",
            "tab s9 fe",
            "samsung tab s9fe+",
            "samsung tab s9fe plus",
            "s9fe tablet",
            "s9 fe tablet",
            "s9 fe+ tablet"
        ],
        "IPHONE 14PRO": [
            "ip14pro",
            "iphone14 pro",
            "14pro",
            "iphone 14 pro",
            "iphone14 pro",
            "iphone 14pro",
            "iphone14pro",
            "i phone 14 pro",
            "apple iphone 14 pro",
            "apple iphone14pro",
            "14 pro iphone",
            "14pro iphone",
            "iphone 14 professional",
            "iphone 14 pro phone",
            "iphone 14 pro mobile",
            "iphone14pro apple",
            "iphone 14pro model",
            "iphone fourteen pro",
            "iphone fourteen pro apple",
            "14 iphone pro",
            "14 iphone pro apple"
        ],
        "SAMSUNG FLIP6": [
            "samsung flip 6",
            "samsung flip6",
            "galaxy flip 6",
            "galaxy flip6",
            "galaxy z flip 6",
            "flip 6",
            "flip6",
            "flip6 samsung",
            "flip 6 samsung",
            "z flip 6",
            "zflip6",
            "flip 6 z",
            "flip 6 phone",
            "flip6 phone",
            "samsung z flip 6",
            "samsung zflip6",
            "galaxy zflip6",
            "flip 6 mobile",
            "flip6 mobile",
            "flip6 device"
        ],
        "IPHONE 17PROMAX": [
            "ip17promax",
            "iphone17 promax",
            "17pm",
            "ip17pm"
            "iphone 17 pro max",
            "iphone17 pro max",
            "iphone 17promax",
            "iphone17promax",
            "i phone 17 pro max",
            "apple iphone 17 pro max",
            "apple iphone17promax",
            "17 pro max iphone",
            "17 pro max iphonex",
            "17promax iphone",
            "iphone 17 pro max phone",
            "iphone 17 pro max mobile",
            "iphone17pro max",
            "iphone 17promax apple",
            "iphone seventeen pro max",
            "iphone17promax device",
            "17 iphone pro max",
            "iphone 17 pro max model"
        ],
        "IPAD AIR5 (2022) (10.9)": [
            "ipad air 5",
            "ipad air5",
            "ipadair5",
            "ipad air 2022",
            "ipad 2022 air 5",
            "ipad 5 air",
            "air 5 ipad",
            "air 5 ipad 10.9",
            "ipad air 5 10.9",
            "ipad air 5 tablet",
            "ipad 10.9",
            "ipad air 10.9",
            "ipadair5 10.9",
            "ipad air five",
            "ipad air five 2022",
            "ipad air 5 device",
            "ipad 5 tablet",
            "ipad air 5 mobile",
            "ipad air5 10.9",
            "ipad air five tablet"
        ],
        "IPAD PRO13 (2024)": [
            "ipad pro 13",
            "ipad pro13",
            "ipadpro13",
            "ipad pro 2024 13",
            "ipad 2024 pro 13",
            "13 inch ipad pro",
            "13 ipad pro",
            "ipad pro 13 inch",
            "ipad pro 13 tablet",
            "ipad pro 13 device",
            "ipad pro thirteen",
            "ipad pro thirteen 2024",
            "ipad pro thirteen inch",
            "ipad pro 13 apple",
            "ipad pro13 apple",
            "ipadpro13 tablet",
            "ipad pro 13 mobile",
            "ipad pro 13 model",
            "ipad 13 pro",
            "ipad 13 pro 2024"
        ],
        "REDMI PAD 5": [
            "redmi pad 5",
            "redmi pad5",
            "redmipad5",
            "mi pad 5",
            "mi pad5",
            "mipad5",
            "pad 5 redmi",
            "pad5 redmi",
            "pad 5 mi",
            "pad5 mi",
            "redmi tablet 5",
            "mi tablet 5",
            "redmi pad 5 tablet",
            "mi pad 5 tablet",
            "redmi pad 5 device",
            "pad 5 redmi tablet",
            "pad 5 mi tablet",
            "redmi 5 pad",
            "mi 5 pad",
            "pad five redmi"
        ],
        "SAMSUNG S9+": [
            "samsung s9+",
            "samsung s9 plus",
            "galaxy s9 plus",
            "galaxy s9+",
            "s9 plus",
            "s9+",
            "s9plus",
            "samsung s9plus",
            "galaxy s9plus",
            "s9 plus samsung",
            "s9 samsung plus",
            "s9+ samsung",
            "s9 phone",
            "s9 plus phone",
            "s9 mobile",
            "s9 plus mobile",
            "s9 device",
            "s9 plus device",
            "s9plus samsung",
            "samsung galaxy s9 plus"
        ],
        "IPAD PRO (5TH GEN) (2021) (11)": [
            "ipad pro 11 2021",
            "ipad pro 5th gen 11",
            "ipad pro 5th gen 2021 11",
            "pro 11 2021",
            "pro 11 ipad",
            "ipad pro 11",
            "ipad pro11",
            "ipadpro11",
            "ipad pro 11 tablet",
            "ipad pro 11 device",
            "ipad pro eleven",
            "ipad pro eleven 2021",
            "ipad pro 11 inch",
            "ipad pro 11 2021 tablet",
            "ipad 11 pro",
            "ipad 11 pro 2021",
            "ipad pro five gen 11",
            "ipad pro 5th gen eleven",
            "ipadpro11 2021",
            "ipad 2021 pro 11"
        ],
        "SAMSUNG WATCH 38MM": [
            "samsung watch 38mm",
            "samsung watch 38 mm",
            "samsungwatch38mm",
            "samsungwatch 38mm",
            "galaxy watch 38mm",
            "galaxy watch 38 mm",
            "watch 38mm",
            "watch 38 mm",
            "38mm watch",
            "38 mm watch",
            "samsung smartwatch 38mm",
            "galaxy smartwatch 38mm",
            "watch 38 device",
            "watch 38 phone",
            "38 watch samsung",
            "38 watch galaxy",
            "samsung watch38mm",
            "galaxy watch38mm",
            "smartwatch 38mm",
            "38mm smartwatch"
        ],
        "SAMSUNG S23FE": [
            "samsung s23 fe",
            "samsung s23fe",
            "galaxy s23 fe",
            "galaxy s23fe",
            "s23 fe",
            "s23fe",
            "s23 fe samsung",
            "s23fe samsung",
            "s23 fe galaxy",
            "s23fe galaxy",
            "s23fe phone",
            "s23 fe phone",
            "s23fe mobile",
            "s23 fe mobile",
            "s23fe device",
            "s23 fe device",
            "samsung galaxy s23 fe",
            "s23 fe pro",
            "s23 fe model",
            "s23fe model"
        ],
        "SAMSUNG TAB S7FE": [
            "tab s7 fe",
            "tab s7fe",
            "tabs7fe",
            "s7 fe tab",
            "s7fe tab",
            "samsung s7 fe tablet",
            "samsung tab s7 fe",
            "samsung tab s7fe",
            "galaxy tab s7 fe",
            "galaxy tab s7fe",
            "tab s7 fe samsung",
            "tab s7fe samsung",
            "tab s7 fe galaxy",
            "tab s7fe galaxy",
            "s7 fe tablet",
            "s7fe tablet",
            "tab s7 fe device",
            "tab s7fe device",
            "samsung s7fe",
            "galaxy s7fe"
        ],
        "SAMSUNG TAB A9": [
            "samsung tab a9",
            "tab a9",
            "taba9",
            "samsung taba9",
            "galaxy tab a9",
            "tab a9 samsung",
            "taba9 samsung",
            "tab a9 galaxy",
            "taba9 galaxy",
            "samsung galaxy tab a9",
            "a9 tab",
            "a9 tab samsung",
            "a9 tab galaxy",
            "tab a9 tablet",
            "taba9 tablet",
            "tab a9 device",
            "taba9 device",
            "samsung tab a9 tablet",
            "galaxy taba9",
            "tab a9 phone"
        ],
        "IPAD 10.9 10TH GENERATION": [
            "ipad 10th gen",
            "ipad 10.9 10th",
            "ipad 10.9",
            "ipad10.9",
            "ipad 2022",
            "ipad 10th generation",
            "ipad 10.9 tablet",
            "ipad 10th gen tablet",
            "10th gen ipad",
            "10th gen ipad 2022",
            "ipad tenth generation",
            "ipad tenth gen",
            "ipad 10th gen device",
            "ipad 10.9 device",
            "ipad 10th tablet",
            "ipad10.9 2022",
            "ipad 2022 10.9",
            "ipad 2022 tablet",
            "ipad 10.9 model",
            "ipad 10th gen model"
        ],
        "SAMSUNG FOLD5": [
            "samsung fold 5",
            "samsung fold5",
            "galaxy fold 5",
            "galaxy fold5",
            "z fold 5",
            "zfold5",
            "fold 5",
            "fold5",
            "5 fold",
            "5 fold samsung",
            "fold 5 samsung",
            "5 fold galaxy",
            "fold 5 galaxy",
            "samsung z fold 5",
            "fold5 device",
            "fold 5 device",
            "fold5 phone",
            "fold 5 phone",
            "fold5 samsung",
            "fold5 galaxy"
        ],
        "IPHONE 17PRO": [
            "ip17pro",
            "ip17p",
            "17pro",
            "17p",
            "17 pro",
            "iphone 17 pro",
            "iphone17 pro",
            "iphone17pro",
            "i phone 17 pro",
            "apple iphone 17 pro",
            "17 pro iphone",
            "17 pro iphone 17",
            "iphone 17 pro phone",
            "iphone 17 pro mobile",
            "iphone17 pro device",
            "iphone17pro device",
            "17 iphone pro",
            "17 iphone pro phone",
            "iphone17pro apple",
            "iphone 17 pro model",
            "iphone 17 pro mobile device",
            "iphone 17 pro gadget",
            "iphone 17pro tablet",
            "iphone seventeen pro",
            "iphone seventeen pro device"
        ],
        "SAMSUNG TAB S9+": [
            "tab s9 plus",
            "tab s9plus",
            "tabs9+",
            "tabs9plus",
            "s9 plus tab",
            "s9plus tab",
            "samsung tab s9+",
            "samsung tab s9 plus",
            "galaxy tab s9 plus",
            "galaxy tab s9+",
            "tab s9 plus samsung",
            "tab s9plus samsung",
            "tab s9 plus galaxy",
            "tab s9plus galaxy",
            "s9 plus tablet",
            "s9plus tablet",
            "tab s9 plus device",
            "tab s9plus device",
            "samsung tab s9plus",
            "galaxy tab s9plus"
        ],
        "SAMSUNG FLIP5": [
            "samsung flip 5",
            "samsung flip5",
            "galaxy flip 5",
            "galaxy flip5",
            "z flip 5",
            "zflip5",
            "flip 5",
            "flip5",
            "5 flip",
            "5 flip samsung",
            "flip 5 samsung",
            "5 flip galaxy",
            "flip 5 galaxy",
            "samsung z flip 5",
            "flip5 device",
            "flip 5 device",
            "flip5 phone",
            "flip 5 phone",
            "flip5 samsung",
            "flip5 galaxy"
        ],
        "IPHONE 13PROMAX": [
            "ip13promax",
            "iphone13 promax",
            "13pm",
            "13 pro max",
            "13 promax",
            "iphone 13 pro max",
            "iphone13 pro max",
            "iphone13promax",
            "i phone 13 pro max",
            "apple iphone 13 pro max",
            "13 pro max iphone",
            "13 pro max iphone 13",
            "iphone 13 pro max phone",
            "iphone 13 pro max mobile",
            "iphone13 pro max device",
            "iphone13promax device",
            "13 iphone pro max",
            "13 iphone pro max phone",
            "iphone13promax apple",
            "iphone 13 pro max model",
            "iphone 13promax",
            "iphone thirteen pro max",
            "iphone thirteen pro max device",
            "iphone13promax phone",
            "iphone 13 pro max gadget"
        ],
        "SAMSUNG S23+": [
            "samsung s23+",
            "samsung s23 plus",
            "galaxy s23+",
            "galaxy s23 plus",
            "s23+",
            "s23 plus",
            "s23plus",
            "samsung s23plus",
            "galaxy s23plus",
            "s23 plus samsung",
            "s23+ samsung",
            "s23 plus galaxy",
            "s23+ galaxy",
            "s23 plus phone",
            "s23+ phone",
            "s23plus phone",
            "s23 plus mobile",
            "s23+ mobile",
            "s23plus mobile",
            "s23 plus device"
        ],
        "SAMSUNG S23": [
            "samsung s23",
            "galaxy s23",
            "s23",
            "s23 samsung",
            "s23 galaxy",
            "s23 phone",
            "s23 mobile",
            "s23 device",
            "s23 model",
            "s23 gadget",
            "s23 smartphone",
            "samsung s23 phone",
            "samsung s23 mobile",
            "galaxy s23 phone",
            "galaxy s23 mobile",
            "s23 samsung phone",
            "s23 galaxy phone",
            "s23 samsung mobile",
            "s23 galaxy mobile",
            "s23 smartphone device"
        ],
        "IPHONE 12PRO": [
            "ip12 pro",
            "iphone12 pro",
            "12 pro",
            "12p",
            "12pro",
            "iphone 12 pro",
            "iphone12 pro",
            "iphone12pro",
            "i phone 12 pro",
            "apple iphone 12 pro",
            "12 pro iphone",
            "12 pro iphone 12",
            "iphone 12 pro phone",
            "iphone 12 pro mobile",
            "iphone12 pro device",
            "iphone12pro device",
            "12 iphone pro",
            "12 iphone pro phone",
            "iphone12pro apple",
            "iphone 12 pro model",
            "iphone twelve pro",
            "iphone twelve pro device",
            "iphone12pro phone",
            "iphone 12pro gadget",
            "12 pro apple iphone"
        ],
        "SAMSUNG S22ULTRA": [
            "samsung s22 ultra",
            "samsung s22ultra",
            "galaxy s22 ultra",
            "galaxy s22ultra",
            "s22 ultra",
            "s22ultra",
            "ultra s22",
            "ultra s22 samsung",
            "ultra s22 galaxy",
            "s22 ultra samsung",
            "s22ultra samsung",
            "s22 ultra galaxy",
            "s22ultra galaxy",
            "s22 ultra phone",
            "s22ultra phone",
            "s22 ultra mobile",
            "s22ultra mobile",
            "s22 ultra device",
            "s22ultra device",
            "s22 ultra model",
            "s22ultra gadget"
        ],
        "IPAD PRO (6TH GEN) (2022) (11)": [
            "ipad pro 11 2022",
            "ipad pro 6th gen 11",
            "ipad pro 11",
            "ipadpro11",
            "ipadpro 11",
            "11 ipad pro",
            "11 ipad pro 2022",
            "ipad pro eleven",
            "ipad pro eleven 2022",
            "ipad pro 11 tablet",
            "ipad pro 6th gen tablet",
            "ipad pro 11 device",
            "ipad pro 6th gen device",
            "ipad pro 2022",
            "ipad pro 11 model",
            "ipad pro 11 apple",
            "ipadpro11 device",
            "ipad pro eleven device",
            "ipad 11 pro",
            "ipad 11 pro 2022"
        ],
        "IPAD AIR11 (2024)": [
            "ipad air 11",
            "ipad air 2024 11",
            "ipadair11",
            "ipadair 11",
            "11 ipad air",
            "11 ipad air 2024",
            "ipad air eleven",
            "ipad air eleven 2024",
            "ipad air 11 tablet",
            "ipad air 2024 tablet",
            "ipad air 11 device",
            "ipad air eleven device",
            "ipad air 11 model",
            "ipad air 11 apple",
            "ipad 11 air",
            "ipad 11 air 2024",
            "ipad air 2024",
            "ipad air 2024 model",
            "ipadair11 device",
            "ipad air eleven tablet"
        ],
        "APPLE IWATCH 49MM": [
            "apple watch 49mm",
            "apple watch 49",
            "iwatch 49mm",
            "iwatch49mm",
            "iwatch 49",
            "49mm apple watch",
            "49 apple watch",
            "49mm iwatch",
            "49 iwatch",
            "apple iwatch 49mm",
            "apple iwatch 49",
            "iwatch 49mm apple",
            "iwatch 49 apple",
            "apple watch 49mm device",
            "iwatch 49mm device",
            "apple watch 49mm smartwatch",
            "iwatch49 device",
            "iwatch49mm smartwatch",
            "49mm apple smartwatch",
            "49 iwatch device"
        ],
        "AIRPODS 1 / 2": [
            "airpods 1",
            "airpods 2",
            "airpods1",
            "airpods2",
            "airpods 1 2",
            "airpods gen 1",
            "airpods gen 2",
            "airpods gen 1 2",
            "apple airpods 1",
            "apple airpods 2",
            "apple airpods1",
            "apple airpods2",
            "airpods 1 wireless",
            "airpods 2 wireless",
            "airpods 1 earbuds",
            "airpods 2 earbuds",
            "airpods 1 device",
            "airpods 2 device",
            "airpods 1 headphones",
            "airpods 2 headphones"
        ],
        "IPAD PRO (5TH GEN) (2021) (12.9)": [
            "ipad pro 12.9 2021",
            "ipad pro 5th gen 12.9",
            "ipad pro 12.9",
            "ipadpro12.9",
            "ipadpro 12.9",
            "12.9 ipad pro",
            "12.9 ipad pro 2021",
            "ipad pro twelve point nine",
            "ipad pro twelve point nine 2021",
            "ipad pro 12.9 tablet",
            "ipad pro 5th gen tablet",
            "ipad pro 12.9 device",
            "ipad pro twelve point nine device",
            "ipad pro 12.9 model",
            "ipad pro 12.9 apple",
            "ipad12.9 pro",
            "ipad12.9 pro 2021",
            "ipad pro 5th gen device",
            "ipad pro 12.9 gadget",
            "ipad pro 12.9 apple"
        ],
        "IPAD 5 (5TH GEN) (2017) (9.7)": [
            "ipad 5th gen",
            "ipad 2017 9.7",
            "ipad 5",
            "ipad5",
            "ipad 5 tablet",
            "ipad 5 device",
            "ipad 5th gen tablet",
            "ipad 5th gen device",
            "9.7 ipad",
            "ipad 9.7",
            "ipad 9.7 2017",
            "ipad nine point seven",
            "ipad nine point seven 2017",
            "ipad 5 apple",
            "ipad 5th gen apple",
            "ipad 9.7 apple",
            "ipad 9.7 tablet",
            "ipad 9.7 device",
            "ipad5 device",
            "ipad5 tablet"
        ],
        "IPHONE 16PROMAX": [
            "ip16promax",
            "iphone16",
            "16pm",
            "16 pro max",
            "ip16pm"
            "iphone 16 pro max",
            "iphone16 pro max",
            "iphone16promax",
            "i phone 16 pro max",
            "apple iphone 16 pro max",
            "16 pro max iphone",
            "16 pro max iphone 16",
            "iphone 16 pro max phone",
            "iphone 16 pro max mobile",
            "iphone16 pro max device",
            "iphone16promax device",
            "16 iphone pro max",
            "16 iphone pro max phone",
            "iphone16promax apple",
            "iphone 16 pro max model",
            "iphone sixteen pro max",
            "iphone sixteen pro max device",
            "iphone16promax phone",
            "iphone 16pro max",
            "iphone16pro max phone"
        ],
        "SAMSUNG FOLD7": [
            "samsung fold 7",
            "fold 7 samsung",
            "z fold 7",
            "z fold7",
            "fold7",
            "7 fold",
            "7 fold samsung",
            "7 fold z",
            "samsung z fold 7",
            "galaxy fold 7",
            "galaxy fold7",
            "fold 7 galaxy",
            "fold7 galaxy",
            "fold 7 phone",
            "fold7 phone",
            "fold 7 mobile",
            "fold7 mobile",
            "fold 7 device",
            "fold7 device",
            "samsung fold7 device"
        ],
        "APPLE IWATCH 42MM": [
            "apple watch 42mm",
            "apple watch 42",
            "iwatch 42mm",
            "iwatch42mm",
            "iwatch 42",
            "42mm apple watch",
            "42 apple watch",
            "42mm iwatch",
            "42 iwatch",
            "apple iwatch 42mm",
            "apple iwatch 42",
            "iwatch 42mm apple",
            "iwatch 42 apple",
            "apple watch 42mm device",
            "iwatch 42mm device",
            "apple watch 42mm smartwatch",
            "iwatch42 device",
            "iwatch42mm smartwatch",
            "42mm apple smartwatch",
            "42 iwatch device"
        ],
        "SAMSUNG S25EDGE": [
            "samsung s25 edge",
            "samsung s25edge",
            "galaxy s25 edge",
            "galaxy s25edge",
            "s25 edge",
            "s25edge",
            "edge s25",
            "edge s25 samsung",
            "edge s25 galaxy",
            "s25 edge samsung",
            "s25edge samsung",
            "s25 edge galaxy",
            "s25edge galaxy",
            "s25 edge phone",
            "s25edge phone",
            "s25 edge mobile",
            "s25edge mobile",
            "s25 edge device",
            "s25edge device",
            "s25 edge model",
            "s25edge model"
        ],
        "IPAD 11 (A16)": [
            "ipad 11 a16",
            "ipad a16",
            "ipad11a16",
            "ipad11 a16",
            "11 ipad a16",
            "11 ipad a16 tablet",
            "ipad 11",
            "ipad11",
            "ipad 11 tablet",
            "ipad a16 tablet",
            "ipad 11 device",
            "ipad a16 device",
            "ipad11 device",
            "ipad11 tablet",
            "ipad a16 apple",
            "ipad 11 apple",
            "11 ipad",
            "ipad11 apple",
            "ipad a16 model",
            "ipad 11 model"
        ],
        "SAMSUNG S24": [
            "samsung s24",
            "galaxy s24",
            "s24",
            "s24 samsung",
            "s24 galaxy",
            "s24 phone",
            "s24 mobile",
            "s24 device",
            "samsung s24 phone",
            "samsung s24 mobile",
            "samsung s24 device",
            "galaxy s24 phone",
            "galaxy s24 mobile",
            "galaxy s24 device",
            "s24 model",
            "s24 samsung phone",
            "s24 galaxy phone",
            "s24 smartphone",
            "s24 samsung smartphone",
            "s24 galaxy smartphone"
        ],
        "SAMSUNG TAB S8": [
            "samsung tab s8",
            "galaxy tab s8",
            "tab s8",
            "tabs8",
            "s8 tab",
            "s8 tab samsung",
            "s8 tab galaxy",
            "tab s8 samsung",
            "tab s8 galaxy",
            "samsung s8 tab",
            "galaxy s8 tab",
            "tab s8 tablet",
            "tab s8 device",
            "s8 tablet",
            "s8 device",
            "samsung tab s8 tablet",
            "samsung tab s8 device",
            "galaxy tab s8 tablet",
            "galaxy tab s8 device",
            "tab s8 model"
        ],
        "IPAD AIR4 (2020) (10.9)": [
            "ipad air 4",
            "ipad air 2020",
            "ipadair4",
            "ipad air4",
            "air 4 ipad",
            "ipad 4",
            "ipad 4 tablet",
            "ipadair4 tablet",
            "ipad air 4 tablet",
            "ipad air 4 device",
            "ipad air4 device",
            "ipad 4 device",
            "air 4 ipad tablet",
            "air 4 ipad device",
            "ipad air 2020 tablet",
            "ipad air 2020 device",
            "ipadair4 10.9",
            "ipad air4 10.9",
            "ipad air 4 10.9",
            "ipad 4 10.9"
        ],
        "SAMSUNG S24ULTRA": [
            "samsung s24 ultra",
            "galaxy s24 ultra",
            "s24 ultra",
            "s24ultra",
            "ultra s24",
            "ultra s24 samsung",
            "ultra s24 galaxy",
            "s24 ultra samsung",
            "s24ultra samsung",
            "s24 ultra galaxy",
            "s24ultra galaxy",
            "s24 ultra phone",
            "s24ultra phone",
            "s24 ultra mobile",
            "s24ultra mobile",
            "s24 ultra device",
            "s24ultra device",
            "s24 ultra model",
            "s24ultra model",
            "s24ultra smartphone"
        ],
        "REDMI PAD 6": [
            "redmi pad 6",
            "mi pad 6",
            "redmipad6",
            "pad 6 redmi",
            "pad6 redmi",
            "pad6",
            "pad 6",
            "redmi pad6",
            "mi pad6",
            "pad 6 tablet",
            "pad6 tablet",
            "pad 6 device",
            "pad6 device",
            "redmi pad 6 tablet",
            "mi pad 6 tablet",
            "redmi pad 6 device",
            "mi pad 6 device",
            "pad6 redmi device",
            "pad 6 redmi tablet",
            "redmi pad6 device"
        ],
        "SAMSUNG TAB S9": [
            "samsung tab s9",
            "galaxy tab s9",
            "tab s9",
            "tabs9",
            "s9 tab",
            "s9 tab samsung",
            "s9 tab galaxy",
            "tab s9 samsung",
            "tab s9 galaxy",
            "samsung s9 tab",
            "galaxy s9 tab",
            "tab s9 tablet",
            "tab s9 device",
            "s9 tablet",
            "s9 device",
            "samsung tab s9 tablet",
            "samsung tab s9 device",
            "galaxy tab s9 tablet",
            "galaxy tab s9 device",
            "tab s9 model"
        ],
        "IPHONE 16E": [
            "ip16e",
            "iphone16e",
            "16e",
            "ip16 e",
            "iphone 16e",
            "iphone16e",
            "iphone16 e",
            "16e iphone",
            "16e iphone phone",
            "16e iphone mobile",
            "16e iphone device",
            "apple iphone 16e",
            "i phone 16e",
            "iphone 16 e",
            "iphone16e phone",
            "iphone16e mobile",
            "iphone16e device",
            "iphone 16e device",
            "iphone 16e phone",
            "iphone 16e mobile",
            "iphone16e model",
            "16e iphone model",
            "apple iphone 16e device",
            "iphone16e apple"
        ],
        "ONEPLUS PAD GO": [
            "oneplus pad go",
            "pad go oneplus",
            "onepluspadgo",
            "padgo",
            "pad go",
            "oneplus padgo",
            "padgo oneplus",
            "pad go oneplus tablet",
            "padgo tablet",
            "oneplus pad go tablet",
            "pad go device",
            "padgo device",
            "oneplus pad go device",
            "pad go oneplus device",
            "oneplus pad go model",
            "padgo oneplus model",
            "oneplus padgo tablet",
            "padgo oneplus tablet",
            "oneplus pad go apple",   
            "padgo oneplus gadget"
        ],
        "AIRPODS PRO3": [
            "airpods pro 3",
            "pro 3 airpods",
            "airpodspro3",
            "airpods pro3",
            "pro3 airpods",
            "airpods 3 pro",
            "airpods pro 3 apple",
            "airpods pro 3 device",
            "airpods pro3 device",
            "pro3 airpods device",
            "airpods pro 3 earbuds",
            "pro3 airpods earbuds",
            "airpods pro 3 wireless",
            "airpods pro3 wireless",
            "apple airpods pro 3",
            "apple airpods pro3",
            "airpods pro3 model",
            "pro3 airpods model",
            "airpods pro3 apple",
            "airpods pro3 gadget"
        ],
        "SAMSUNG TAB S8+": [
            "tab s8 plus",
            "samsung tab s8+",
            "tabs8plus",
            "s8 plus tab",
            "s8 plus tab samsung",
            "tab s8 plus samsung",
            "samsung tab s8 plus",
            "tab s8 plus galaxy",
            "s8 plus tab galaxy",
            "tab s8 plus tablet",
            "tabs8plus tablet",
            "tab s8 plus device",
            "s8 plus tab device",
            "s8 plus tablet",
            "tabs8plus device",
            "samsung s8 plus tab",
            "galaxy tab s8 plus",
            "tab s8 plus model",
            "s8 plus tab model",
            "tab s8 plus gadget"
        ],
        "IPHONE 13": [
            "ip13",
            "iphone13",
            "13",
            "iphone 13",
            "apple iphone 13",
            "iphone13",
            "i phone 13",
            "13 iphone",
            "13 iphone phone",
            "13 iphone mobile",
            "iphone 13 phone",
            "iphone 13 mobile",
            "iphone13 phone",
            "iphone13 mobile",
            "iphone 13 device",
            "iphone13 device",
            "apple iphone13",
            "apple iphone 13 device",
            "iphone 13 model",
            "iphone13 model",
            "13 iphone device",
            "13 iphone model",
            "iphone 13 gadget"
        ],
        "SAMSUNG S25+": [
            "samsung s25+",
            "galaxy s25 plus",
            "s25+",
            "s25 plus",
            "s25plus",
            "plus s25",
            "plus s25 samsung",
            "s25+ samsung",
            "s25 plus samsung",
            "plus s25 galaxy",
            "s25+ galaxy",
            "s25 plus galaxy",
            "s25+ phone",
            "s25 plus phone",
            "s25+ mobile",
            "s25 plus mobile",
            "s25+ device",
            "s25 plus device",
            "s25 plus model",
            "s25+ model"
        ],
        "AIRPODS PRO": [
            "airpods pro",
            "apple airpods pro",
            "airpodspro",
            "airpods pro apple",
            "pro airpods",
            "pro airpods apple",
            "airpods pro device",
            "airpodspro device",
            "pro airpods device",
            "airpods pro earbuds",
            "airpodspro earbuds",
            "pro airpods earbuds",
            "airpods pro wireless",
            "airpodspro wireless",
            "pro airpods wireless",
            "apple airpodspro",
            "apple airpods pro device",
            "airpods pro model",
            "airpodspro model",
            "pro airpods model"
        ],
        "SAMSUNG TAB S7": [
            "samsung tab s7",
            "galaxy tab s7",
            "tab s7",
            "tabs7",
            "s7 tab",
            "s7 tab samsung",
            "s7 tab galaxy",
            "tab s7 samsung",
            "tab s7 galaxy",
            "samsung s7 tab",
            "galaxy s7 tab",
            "tab s7 tablet",
            "tabs7 tablet",
            "tab s7 device",
            "s7 tab device",
            "s7 tablet",
            "tabs7 device",
            "samsung tab s7 tablet",
            "galaxy tab s7 tablet",
            "tab s7 model"
        ],
        "IPHONE 16PRO": [
            "ip16pro",
            "iphone16pro",
            "16 pro",
            "ip16 pro",
            "iphone 16 pro",
            "16 pro iphone",
            "iphone16pro",
            "iphone16 pro",
            "16pro iphone",
            "iphone 16 pro phone",
            "iphone16pro phone",
            "16 pro iphone phone",
            "iphone 16 pro mobile",
            "iphone16pro mobile",
            "16 pro iphone mobile",
            "iphone 16 pro device",
            "iphone16pro device",
            "16 pro iphone device",
            "apple iphone 16 pro",
            "apple iphone16pro",
            "i phone 16 pro",
            "iphone 16 pro model",
            "iphone16pro model",
            "16 pro iphone model"
        ],
        "AIRPODS PRO2": [
            "airpods pro 2",
            "pro 2 airpods",
            "airpodspro2",
            "airpods pro2",
            "pro2 airpods",
            "airpods 2 pro",
            "airpods pro 2 apple",
            "airpods pro 2 device",
            "airpodspro2 device",
            "pro2 airpods device",
            "airpods pro 2 earbuds",
            "airpodspro2 earbuds",
            "pro2 airpods earbuds",
            "airpods pro 2 wireless",
            "airpodspro2 wireless",
            "pro2 airpods wireless",
            "apple airpods pro 2",
            "apple airpods pro2",
            "airpods pro2 model",
            "pro2 airpods model"
        ],
        "IPHONE 15PLUS": [
            "ip15plus",
            "iphone15plus",
            "15+",
            "15 plus",
            "15plus",
            "ip15+",
            "iphone 15 plus",
            "15 plus iphone",
            "iphone15plus",
            "iphone15 plus",
            "15plus iphone",
            "iphone 15 plus phone",
            "iphone15plus phone",
            "15 plus iphone phone",
            "iphone 15 plus mobile",
            "iphone15plus mobile",
            "15 plus iphone mobile",
            "iphone 15 plus device",
            "iphone15plus device",
            "15 plus iphone device",
            "apple iphone 15 plus",
            "apple iphone15plus",
            "i phone 15 plus",
            "iphone 15 plus model",
            "iphone15plus model",
            "15 plus iphone model"
        ],
        "IPHONE 13PRO": [
            "ip13p",
            "iphone13 pro",
            "13p",
            "13 pro",
            "13pro",
            "iphone 13 pro",
            "13 pro iphone",
            "iphone13pro",
            "iphone13 pro",
            "13pro iphone",
            "iphone 13 pro phone",
            "iphone13pro phone",
            "13 pro iphone phone",
            "iphone 13 pro mobile",
            "iphone13pro mobile",
            "13 pro iphone mobile",
            "iphone 13 pro device",
            "iphone13pro device",
            "13 pro iphone device",
            "apple iphone 13 pro",
            "apple iphone13pro",
            "i phone 13 pro",
            "iphone 13 pro model",
            "iphone13pro model",
            "13 pro iphone model"
        ],
        "IPHONE 17AIR": [
            "ip17 ar",
            "iphone17ar",
            "17ar",
            "17 air",
            "17air",
            "ip17 air",
            "17 ar",
            "iphone 17 air",
            "17 air iphone",
            "iphone17air",
            "iphone17 air",
            "17air iphone",
            "iphone 17 air phone",
            "iphone17air phone",
            "17 air iphone phone",
            "iphone 17 air mobile",
            "iphone17air mobile",
            "17 air iphone mobile",
            "iphone 17 air device",
            "iphone17air device",
            "17 air iphone device",
            "apple iphone 17 air",
            "apple iphone17air",
            "i phone 17 air",
            "iphone 17 air model",
            "iphone17air model",
            "17 air iphone model"
        ],
        "SAMSUNG TAB S8 ULTRA": [
            "tab s8 ultra",
            "samsung tab s8 ultra",
            "tabs8ultra",
            "tab s8ultra",
            "s8 ultra tab",
            "s8 ultra tab samsung",
            "s8 ultra tab galaxy",
            "tab s8 ultra samsung",
            "tab s8 ultra galaxy",
            "samsung s8 ultra tab",
            "galaxy s8 ultra tab",
            "tab s8 ultra tablet",
            "tabs8ultra tablet",
            "tab s8 ultra device",
            "s8 ultra tab device",
            "s8 ultra tablet",
            "tabs8ultra device",
            "samsung tab s8 ultra tablet",
            "galaxy tab s8 ultra tablet",
            "tab s8 ultra model"
        ],
        "IPHONE 17": [
            "iphone 17",
            "apple iphone 17",
            "iphone17",
            "iphone 17 phone",
            "iphone17 phone",
            "iphone 17 mobile",
            "iphone17 mobile",
            "iphone 17 device",
            "iphone17 device",
            "apple iphone17",
            "i phone 17",
            "iphone 17 model",
            "iphone17 model",
            "iphone 17 gadget",
            "apple iphone 17 device"
        ],
        "IPHONE 12PROMAX": [
            "ip12promax",
            "iphone12promax",
            "12promax",
            "12 pro max",
            "12promax",
            "ip12 pro",
            "12pm",
            "ip12pm",
            "ip12 pro max",
            "iphone 12 pro max",
            "12 pro max iphone",
            "iphone12promax",
            "iphone12 pro max",
            "12promax iphone",
            "iphone 12 pro max phone",
            "iphone12promax phone",
            "12 pro max iphone phone",
            "iphone 12 pro max mobile",
            "iphone12promax mobile",
            "12 pro max iphone mobile",
            "iphone 12 pro max device",
            "iphone12promax device",
            "12 pro max iphone device",
            "apple iphone 12 pro max",
            "apple iphone12promax",
            "i phone 12 pro max",
            "iphone 12 pro max model",
            "iphone12promax model",
            "12 pro max iphone model"
        ],
        "ONEPLUS PAD 2 (12.1)": [
            "oneplus pad 2",
            "pad 2 12.1 oneplus",
            "oneplus pad2",
            "oneplus pad 2 tablet",
            "pad2 oneplus",
            "pad 2 oneplus tablet",
            "one plus pad 2",
            "oneplus pad 2 device",
            "pad 2 12.1",
            "pad 2 12.1 device",
            "pad2 tablet",
            "oneplus pad 2 model"
        ],
        "SAMSUNG TAB S9FE": [
            "tab s9 fe",
            "samsung tab s9 fe",
            "tabs9fe",
            "s9 fe tab",
            "tab s9fe samsung",
            "tab s9 fe device",
            "samsung s9 fe tab",
            "galaxy tab s9 fe",
            "tab s9 fe tablet",
            "s9 fe tablet",
            "tabs9fe tablet",
            "tab s9 fe model"
        ],
        "SAMSUNG TAB A (10.5) T595": [
            "tab a 10.5",
            "samsung t595",
            "tab a t595",
            "tab a 10.5 samsung",
            "tab a 10.5 tablet",
            "samsung tab a 10.5",
            "tab a device",
            "t595 tablet",
            "tab a 10.5 device",
            "tab a 10.5 model"
        ],
        "REDMI PAD PRO (12.1)": [
            "redmi pad pro",
            "pad pro 12.1 redmi",
            "redmi padpro",
            "pad pro redmi",
            "pad pro tablet",
            "redmi pad pro tablet",
            "padpro 12.1",
            "redmi pad pro device",
            "pad pro 12.1 device",
            "pad pro model"
        ],
        "SAMSUNG FOLD3": [
            "samsung fold 3",
            "z fold 3",
            "fold 3 samsung",
            "fold3",
            "samsung fold3",
            "z fold3",
            "3 fold samsung",
            "3 fold",
            "fold 3 device",
            "fold3 device",
            "samsung fold 3 device",
            "z fold 3 device",
            "fold 3 phone",
            "fold3 phone",
            "samsung fold 3 phone",
            "z fold 3 phone",
            "fold 3 model",
            "fold3 model",
            "samsung fold3 model",
            "z fold3 model"
        ],
        "IPHONE 16": [
            "ip16",
            "iphone16",
            "16",
            "iphone 16",
            "apple iphone 16",
            "iphone16",
            "iphone 16 phone",
            "iphone16 phone",
            "iphone 16 mobile",
            "iphone16 mobile",
            "iphone 16 device",
            "iphone16 device",
            "apple iphone16",
            "i phone 16",
            "iphone 16 model",
            "iphone16 model",
            "iphone 16 gadget",
            "apple iphone 16 device"
        ],
        "IPHONE 16PLUS": [
            "iphone 16 plus",
            "16 plus iphone",
            "iphone16plus",
            "iphone16 plus",
            "16plus iphone",
            "iphone 16 plus phone",
            "iphone16plus phone",
            "16 plus iphone phone",
            "iphone 16 plus mobile",
            "iphone16plus mobile",
            "16 plus iphone mobile",
            "iphone 16 plus device",
            "iphone16plus device",
            "16 plus iphone device",
            "apple iphone 16 plus",
            "apple iphone16plus",
            "i phone 16 plus",
            "iphone 16 plus model",
            "iphone16plus model",
            "16 plus iphone model"
        ],
        "REDMI MI PRO": [
            "redmi mi pro",
            "mi pro redmi",
            "redmi mipro",
            "mi pro",
            "redmi mi pro device",
            "mi pro device",
            "redmi mi pro tablet",
            "mi pro tablet",
            "redmi mi pro model",
            "mi pro model"
        ],
        "REDMI 13PRO": [
            "redmi 13 pro",
            "13 pro redmi",
            "redmi13pro",
            "13pro redmi",
            "redmi 13 pro device",
            "13 pro redmi device",
            "redmi 13 pro tablet",
            "13 pro redmi tablet",
            "redmi 13 pro model",
            "13 pro redmi model"
        ],
        "LENOVO TAB M11": [
            "lenovo tab m11",
            "tab m11",
            "lenovo m11",
            "tab m11 lenovo",
            "lenovo tab m11 tablet",
            "tab m11 tablet",
            "lenovo tab m11 device",
            "tab m11 device",
            "lenovo tab m11 model",
            "m11 lenovo"
        ],
        "IPAD AIR2 (2014) (9.7)": [
            "ipad air 2",
            "ipad air 2014",
            "ipad air2",
            "ipad air 2 tablet",
            "ipad air2 tablet",
            "ipad air 2 device",
            "ipad air2 device",
            "ipad air 2 model",
            "ipad air2 model",
            "ipad 2014 9.7",
            "ipad 9.7 air2"
        ],
        "SAMSUNG S25": [
            "samsung s25",
            "galaxy s25",
            "s25",
            "s25 samsung",
            "s25 galaxy",
            "samsung s25 phone",
            "galaxy s25 phone",
            "s25 phone",
            "samsung s25 device",
            "galaxy s25 device",
            "s25 device",
            "samsung s25 model",
            "galaxy s25 model",
            "s25 model",
            "s25 smartphone",
            "samsung s25 smartphone",
            "galaxy s25 smartphone"
        ],
        "APPLE IWATCH 41MM": [
            "apple watch 41mm",
            "iwatch 41mm",
            "applewatch 41mm",
            "iwatch41mm",
            "apple watch41mm",
            "apple iwatch 41",
            "iwatch 41 mm",
            "apple iwatch41mm",
            "apple watch 41 device",
            "iwatch 41 device",
            "apple iwatch 41 device",
            "iwatch 41 smartwatch",
            "apple watch 41 smartwatch",
            "iwatch41 device",
            "iwatch 41 model",
            "apple iwatch 41 model"
        ],
        "SAMSUNG S23ULTRA": [
            "samsung s23 ultra",
            "galaxy s23 ultra",
            "s23 ultra",
            "s23ultra",
            "samsung s23ultra",
            "galaxy s23ultra",
            "s23 ultra samsung",
            "s23 ultra galaxy",
            "ultra s23",
            "ultra s23 samsung",
            "s23 ultra phone",
            "s23ultra phone",
            "samsung s23 ultra phone",
            "galaxy s23 ultra phone",
            "s23 ultra device",
            "s23ultra device",
            "s23 ultra smartphone",
            "s23ultra smartphone",
            "s23 ultra model",
            "s23ultra model"
        ],
        "LENOVO PAD PLUS": [
            "lenovo pad plus",
            "pad plus lenovo",
            "lenovo padplus",
            "padplus lenovo",
            "pad plus",
            "padplus",
            "lenovo pad plus tablet",
            "pad plus lenovo tablet",
            "lenovo pad plus device",
            "pad plus lenovo device",
            "lenovo pad plus model",
            "pad plus lenovo model",
            "plus pad lenovo",
            "lenovo plus pad",
            "pad plus tablet",
            "padplus device"
        ],
        "SAMSUNG S22+": [
            "samsung s22+",
            "galaxy s22 plus",
            "s22+",
            "s22 plus",
            "s22plus",
            "s22 plus samsung",
            "s22plus samsung",
            "22 plus samsung",
            "samsung s22 plus",
            "galaxy s22+",
            "s22+ phone",
            "s22 plus phone",
            "s22plus phone",
            "s22+ device",
            "s22 plus device",
            "s22plus device",
            "s22+ smartphone",
            "s22 plus smartphone",
            "s22plus smartphone",
            "s22+ model",
            "s22 plus model"
        ],
        "SAMSUNG S25ULTRA": [
            "samsung s25 ultra",
            "galaxy s25 ultra",
            "s25 ultra",
            "s25ultra",
            "samsung s25ultra",
            "galaxy s25ultra",
            "s25 ultra samsung",
            "s25 ultra galaxy",
            "ultra s25",
            "ultra s25 samsung",
            "s25 ultra phone",
            "s25ultra phone",
            "samsung s25 ultra phone",
            "galaxy s25 ultra phone",
            "s25 ultra device",
            "s25ultra device",
            "s25 ultra smartphone",
            "s25ultra smartphone",
            "s25 ultra model",
            "s25ultra model"
        ],
        "IPHONE 15PRO": [
            "ip15p",
            "iphone15 pro",
            "15p",
            "15 pro",
            "15pro",
            "ip15 pro",
            "iphone 15 pro",
            "15 pro iphone",
            "iphone15pro",
            "iphone 15pro",
            "15pro iphone",
            "iphone 15 pro phone",
            "iphone15pro phone",
            "15 pro iphone phone",
            "iphone 15 pro mobile",
            "iphone15pro mobile",
            "15 pro iphone mobile",
            "iphone 15 pro device",
            "iphone15pro device",
            "15 pro iphone device",
            "apple iphone 15 pro",
            "apple iphone15pro",
            "i phone 15 pro",
            "iphone 15 pro model",
            "iphone15pro model",
            "15 pro iphone model"
        ],
            
        "APPLE IWATCH 45MM": [
            "apple watch 45mm",
            "iwatch 45mm",
            "apple smartwatch 45mm",
            "apple series watch 45mm",
            "apple watch large size",
            "apple watch big screen",
            "apple watch 45 millimeter",
            "apple wrist watch 45mm"
        ],
        "APPLE IWATCH 40MM": [
            "apple watch 40mm",
            "iwatch 40mm",
            "apple smartwatch 40mm",
            "apple series watch 40mm",
            "apple watch small size",
            "apple watch compact",
            "apple watch 40 millimeter",
            "apple wrist watch 40mm"
        ],
        "IPHONE 14PROMAX": [
            "ip14max",
            "iphone14promax",
            "14promax",
            "14 pro max",
            "ip14pm",
            "ip14 pm",
            "14 pm",
            "14pm",
            "iphone 14 pro max",
            "14 pro max iphone",
            "apple iphone 14 pro max",
            "iphone 14promax",
            "iphone 14 promax",
            "iphone 14 pro max mobile",
            "iphone 14 pro max smartphone",
            "iphone 14 pro max apple phone",
            "iphone 14 pro max latest model",
            "iphone 14 pro max big size",
            "iphone 14 pro max large screen",
            "iphone 14 pro max 256gb",
            "iphone 14 pro max 512gb"
        ],


        "AIRPODS 3 GENERATION": [
            "airpods 3",
            "airpods 3rd gen",
            "apple airpods 3",
            "airpods third generation",
            "airpods gen 3",
            "airpods 3rd generation",
            "airpods latest model",
            "airpods new version",
            "airpods 2021 model",
            "airpods 3 wireless earbuds",
            "airpods 3 bluetooth headphones",
            "airpods 3 apple earbuds",
            "airpods 3 charging case"
        ],

        "IPHONE 11": [
            "ip11",
            "iphone11",
            "11",
            "iphone 11",
            "apple iphone 11",
            "iphone eleven",
            "iphone 11 smartphone",
            "iphone 11 mobile",
            "iphone 11 apple phone",
            "iphone 11 latest model",
            "iphone 11 64gb",
            "iphone 11 128gb",
            "iphone 11 256gb",
            "iphone 11 black",
            "iphone 11 white",
            "iphone 11 purple",
            "iphone 11 red",
            "iphone 11 green"
        ],

        "SAMSUNG FLIP7": [
            "samsung flip 7",
            "z flip 7",
            "samsung galaxy z flip 7",
            "galaxy flip 7",
            "samsung z flip7",
            "samsung flip7",
            "samsung foldable flip 7",
            "samsung flip phone 7",
            "galaxy z flip seventh gen",
            "samsung flip 7 smartphone",
            "samsung flip 7 mobile",
            "samsung flip 7 latest model",
            "samsung flip 7 256gb",
            "samsung flip 7 512gb"
        ],

        "SAMSUNG S24FE": [
            "samsung s24 fe",
            "galaxy s24 fe",
            "samsung galaxy s24 fe",
            "s24 fe",
            "samsung s24fe",
            "galaxy s24fe",
            "samsung s24 fe smartphone",
            "samsung s24 fe mobile",
            "samsung s24 fe latest model",
            "samsung s24 fe phone",
            "samsung s24 fe 128gb",
            "samsung s24 fe 256gb",
            "samsung s24 fe 512gb",
            "samsung s24 fe colors",
            "samsung s24 fe 2025 edition"
        ],

        "IPHONE 12": [
            "ip12",
            "iphone12",
            "12",
            "iphone 12",
            "apple iphone 12",
            "iphone twelve",
            "iphone 12 smartphone",
            "iphone 12 mobile",
            "iphone 12 apple phone",
            "iphone 12 latest model",
            "iphone 12 64gb",
            "iphone 12 128gb",
            "iphone 12 256gb",
            "iphone 12 blue",
            "iphone 12 black",
            "iphone 12 white",
            "iphone 12 red",
            "iphone 12 green",
            "iphone 12 purple"
        ],

        "IPAD 6 (6TH GEN) (2018) (9.7)": [
            "ipad 6th gen",
            "ipad 2018",
            "apple ipad 6th generation",
            "ipad 6",
            "ipad sixth generation",
            "ipad 2018 9.7 inch",
            "ipad 9.7 2018",
            "ipad 6th gen 2018 model",
            "ipad 2018 edition",
            "ipad 2018 apple tablet",
            "ipad 6th gen tablet",
            "ipad 2018 32gb",
            "ipad 2018 128gb",
            "ipad 2018 wifi",
            "ipad 2018 cellular",
            "ipad 2018 retina display"
        ],

        "IPHONE 15 PRO": [
            "ip15pro",
            "iphone15 pro",
            "15p",
            "15 pro",
            "15pro",
            "ip15 pro",
            "iphone 15 pro",
            "15 pro iphone",
            "apple iphone 15 pro",
            "iphone 15pro",
            "iphone fifteen pro",
            "ip15 pro",
            "ip15p",
            "iphone 15 pro smartphone",
            "iphone 15 pro mobile",
            "iphone 15 pro 128gb",
            "iphone 15 pro 256gb",
            "iphone 15 pro 512gb",
            "iphone 15 pro 1tb"
        ],
        "IPAD PRO11 (2024)": [
            "ipad pro 11 2024",
            "pro 11 ipad 2024",
            "apple ipad pro 11 2024",
            "ipad pro11 2024",
            "ipad pro 11-inch 2024",
            "ipad pro 2024 11",
            "ipad pro 11 latest model",
            "ipad pro 11 2024 tablet"
        ],
        "IPHONE 14": [ "ip14",
            "iphone14",
            "14", "iphone 14", "apple iphone 14", "iphone fourteen", "iphone 14 smartphone", "iphone 14 mobile" ],
        "SAMSUNG FOLD4": [ "samsung fold 4", "z fold 4", "galaxy fold 4", "samsung galaxy z fold4", "fold4 samsung" ],
        "SAMSUNG TAB S7+": [ "tab s7 plus", "samsung tab s7+", "galaxy tab s7 plus", "samsung galaxy tab s7+", "tab s7+" ],
        "SAMSUNG FLIP4": [ "samsung flip 4", "z flip 4", "galaxy flip 4", "samsung galaxy z flip4", "flip4 samsung" ]
        }

        # Ensure phone_modal is a string
        if not isinstance(phone_modal, str):
            phone_modal = str(phone_modal)
        
        extractedname = None
        for key,_ in devices.items():
            if phone_modal.lower() in devices[key]:
                extractedname = key
                print(f"Extracted Name on loop: {extractedname}")
                break
        
        if extractedname:
            return {"phone_model": extractedname}
        else:
            # Return the result of name_extractor
            return name_extractor(file_path, phone_modal)
    
    except Exception as e:
        print(f"An error occurred: {e}")
        return {"phone_model": None}


